### ISSUE TITLE
2020-08-17: [VWS/Covid19NotificationApp] - permissions not asked / set?

### ISSUE THREAD

**Issue by las3r** [minvws/nl-covid19-notification-app-android#11]
### Describe the bug, issue or concern
After the news broke on tweakers.net about the availability of the app on Android I went ahead and installed it. During installation of the app and subsequent opening of the app I wasn't prompted for permissions Regarding Bluetooth usage or usage of the notification api for health providers.

I'm not sure if the app actually works because I don't see any notification of the app running in the background (other than the app telling me it is running).  Also, when I check the permissions that the app has been given (in my settings) I see no permissions set other than it being able to send out "notifications", which is a regular permission.

### To Reproduce
- Install the app from app store
- Open the app

### Expected behavior
- The app asks for permissions Regarding the use of Bluetooth and the notification api 

**Smartphone (please complete the following information):**
 - Device: xiaomi mi 9
 - OS: Android 10 / miui 12

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by donleo123** [comment]
When going into settings, search for corona. Click on exposure notifications. You can see there that the app is working fine.

**Comment by hvisser** [comment]
Bluetooth is a "normal" permission and therefore apps do not have to request it. Exposure notification permission is asked by the framework when you enable the app in the onboarding. It's not technically an Android permission though, but has the same effect and is guarded by the GAEN framework.

**Comment by las3r** [comment]
> When going into settings, search for corona. Click on exposure notifications. You can see there that the app is working fine.

Correct! Thanks for clearing this up!
