### ISSUE TITLE
2020-08-17: [VWS/Covid19NotificationApp] Let user select user interface language

### ISSUE THREAD

**Issue by kdekooter** [minvws/nl-covid19-notification-app-android#12]
### Describe the bug, issue or concern

At the moment it is not possible for the user to select the language of the application. Apparently is it set to the default language of the device.

### To Reproduce
Open the app

### Expected behavior
A settings menu in which the language preference can be set

**Smartphone (please complete the following information):**
 - OS: Android

### Governance
- [ x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by hvisser** [comment]
On Android it's not common to support this, apps should follow the system language set on the device. Technically we could hack around it but it's just that; a hack and not really supported by Google and with lots of potential for issues.

**Comment by avbentem** [comment]
> apps should follow the system language set on the device

Interesting, any source for this claim?

While I don't care much about the language of this very CoronaMelder app (as I don't expect to interact with it much anyway), _in general_ I feel that _forcing_ the OS language is quite horrible. I'm very happy that, e.g., the NS app allows for selecting Dutch. But adding a settings menu for _just_ the language may be a bit of overkill too, I feel.

**Asides**:

- I _assume_ most Android users will be able to select Dutch in their system-wide list of preferred languages, if they want to. 

  (Somehow, my Android 8 device that I purchased from a well-known Dutch webshop was actually released for the German market. Selling imported devices is really business as usual for those webshops: I only discovered that when NL-Alert didn't work. But those imported devices may limit the available languages, though I guess Dutch webshops will ensure Dutch is included on devices they import. On my German device Dutch is indeed available, but, e.g., Afrikaans is not.)

- The app [seems to support](https://github.com/minvws/nl-covid19-notification-app-android/tree/master/app/src/main/res) Arabic, Bulgarian, Dutch, the default English, French, German, Polish, Romanian, Spanish and Turkish. So, a user who has **none** of these languages in their list of preferred languages will get the English version. (I feel that English is a tad weird for a Dutch app, but of course it's an edge case. One could test by adding _only_, say, Catalan to their list of prefered languages.)

- Choosing Dutch on my English Android 8 device would help me supporting others who use the Dutch version. But I guess not much support is needed anyway, and I could temporarily change the order of preferred languages, so not a big deal for me.

- For this very app the English translations seem fine to me; good job!

**Comment by kdekooter** [comment]
Please investigate @hvisser! There are loads of apps providing this feature. 

I could lend a hand if necessary.

**Comment by JolandaVerhoef** [comment]
Hi @kdekooter and @avbentem. We've discussed this topic quite extensively within the team and with other Android developers from our network. Our decision was to follow system language, for these reasons:
1. Technically, the Android platform doesn't like you overriding the OS language. You can make it work, but it comes at a risk of introducing bugs. 
2. Introducing a language picking screen even when we support the language you have set in your OS means an extra step in onboarding. Research shows that with each extra step in onboarding you loose potential users. (sorry, don't have the research here, but I remember it was investigated at some point)
3. Our app relies quite heavily on OS dialogs and notifications (when you give consent to the Exposure Notification framework, when you turn BT or location services off, giving consent to upload your tokens, etc). We can't influence the languages of these dialogs. We want to provide consistency in language while you're using the app, not having two languages intermingle.

Based on these three arguments, we currently have decided to follow OS language. We'll keep track of the feedback we get from various channels. If many users are having troubles with this decision, we can revisit it.

**Comment by kdekooter** [comment]
Good to hear that you have thought this through! Curious to learn how many native Dutch speakers have their device language set to EN like me.

Let's agree to disagree on this feature for now ;-).

**Comment by avbentem** [comment]
Well, including the actual users may change the decision? I see quite a bit of confusion in the reviews on https://play.google.com/store/apps/details?id=nl.rijksoverheid.en&hl=en&showAllReviews=true

> [...] Kritiek: Wel veel engels, ze hadden een Nederlandse vertaling kunnen toevoegen. [...]

> [...] Alleen raar dat de app alleen in het Engels beschikbaar is. Veel mensen haken dan al af. Of is soms door Engelstaligen gemaakt? [...]

> Duidelijk app maar bijzonder dat deze standaard in het Engels is en dat je de taal niet kan wijzigen. Ik heb zelf geen probleem met Engels maar ik ken genoeg mensen die slecht Engels kunnen. Hoe wil je die aan zo'n app krijgen? 

> Why is it in english? Not everyone understands that.

> Zo jammer dat de app alleen engelstalig is! Dit is toch voor Nederland bedoeld?

> Only in English and needs GPS/location rights. [...]

> Waarom is de app Engelstalig !!!!!!

(Some more users complain, but they seem to understand _why_ they're getting the English version.)

**Comment by PanderMusubi** [comment]
Many Dutch (IT) professionals, especially app developers, have their phone configured to English. Only a few apps are set to Dutch, such as weather forecast apps or Marktplaats. The functionality to deveiate from the default device language is common for apps for which it is useful, such as this one.

**Comment by hvisser** [comment]
I think the feature request is clear. I was trying to give some context to why we think it's not as easy as it seems:

* No OS level support for this (unlike iOS, which has a per-app setting)
* No real supported way to implement it on Android
* User experience might be inconsistent due to the dialogs issue that @JolandaVerhoef points out

All are reasons why only a few apps support this on Android generally. CoronaMelder doesn't use Dutch as the "default" language as we want people using the app on a phone language that is not supported by the app to be able to use the app in English, not Dutch, which might not be the case for weather apps and Marktplaats for example.

Of course we will take feedback from reviews and discussions like this into account. So we do really appreciate bringing this up.

**Comment by arjank** [comment]
I don't think the language selection has to be in the onboarding process. I would rather have it available as a setting that can be changed later, so it's not a one time selection. Preferences may change over time, especially in the event that more languages are added.

**Comment by pjbruin** [comment]
It is not at all clear that users whose native/first language is not supported by the app will prefer English over Dutch, especially since they are almost certainly located in the Netherlands. Even though most Dutch speakers have English as their second language, it is likely that many inhabitants of the Netherlands whose first language is neither Dutch nor English will have Dutch as their second language.

**Comment by PanderMusubi** [comment]
Ah, to be clear about apps aimed at the Netherlands (e.g. Marktplaats) and avoid confusion, they work as follows: the start with the system language. Only after onbaording you can choose another language. They don't prefer Dutch or amke assumptions on how many people are native speakers and they don't switch during onboarding.

**Comment by avbentem** [comment]
Aside, and I assume the Android UI team knows, @jorisleker mentioned [in Slack](https://codefornl.slack.com/archives/C011R4NCFMJ/p1597681351113400?thread_ts=1597680861.105600&cid=C011R4NCFMJ):

> Vanuit UX lag er het idee om primair de systeemtaal te volgen, maar als de systeemtaal niet Nederlands is - een scherm aan de onboarding toe te voegen. En daarin iets te te zeggen als: “de app is er ook in het Nederlands, overschakelen?” Er waren eerst wat andere prioriteiten.

I think this may refer to the iOS app, for which language switching is supported by iOS anyhow.

(Slack invite through https://doemee.codefor.nl/)

**Comment by kdekooter** [comment]
Did 30 seconds of googling and I am not buying that language switching in an Android app is complicated. 

See https://stackoverflow.com/questions/18982715/language-switching-inside-app-android

**Comment by oliv3r** [comment]
Maybe interesting to know, that a 'poplar' dutch app (ING banking app) also follows this, where you can select the language via settings (dutch or english only iirc, haven't checked in a while) as i too, have my phone set to English, but actually prefer the ING app to be in dutch ... Probably because the english translations tend to be weird :)

**Comment by lpappalettera** [comment]
In the upcoming release (version 1.3.0) we've added an option to overwrite the system language with Dutch in the settings screen.

**Comment by lpappalettera** [comment]
We've started a staged rollout of 1.3.0 and therefore I will close this issue

**Comment by Richhoef** [comment]
This sadly does not work on my phone. I can  change the toggle, but nothing happens. I have a Xiaomi MI 9 with android 10

**Comment by lpappalettera** [comment]
> This sadly does not work on my phone. I can change the toggle, but nothing happens. I have a Xiaomi MI 9 with android 10

Thanks for reporting this, i will add a ticket to our internal board to investigate the issue.
