### ISSUE TITLE
[2020-08-17]: [VWS/Covid19NotificationApp] Add option to temporarily disable the app

### ISSUE THREAD

**Issue by pmeijers** [minvws/nl-covid19-notification-app-android#13]
Issue:
It is not (clearly) obvious how to temporarily disable the app, without completely deleting it from your phone. Via phone settings you can deactivate "blootstellingsmeldingen".

Proposal:
It would be nice to use the "check" button in the app to mute the app for a while.

**Comment by hvisser** [comment]
That's a great suggestion and we are exploring how we can support this and what's technically possible for this scenario.

**Comment by pmeijers** [comment]
You're welcome! Happy to be able to contribute to this project.

You may think of using the check sign at top of the app, changing it into a button, by (de)activating the 'blootstellingsmeldingen' of the phone's settings.

Regards,
Paul

Outlook for Android<https://aka.ms/ghei36> downloaden

________________________________

**Comment by lpappalettera** [comment]
@pmeijers FYI: we've released feature to temporarily disable the app (app version 1.2). You can pause the app from the in-app settings screen. Hopefully this suits your expectations.
