### ISSUE TITLE
2020-08-18: [VWS/Covid19NotificationApp] Additional information appears to be needed to build a fully functional app

### ISSUE THREAD

**Issue by dennisjaheruddin** [minvws/nl-covid19-notification-app-android#20]
### Describe the bug, issue or concern

This app is explained to be open source. To ensure there are no hidden gems, people should be able to compile it themselves.
For this a good amount of capability may be assumed, but it should be possible with the code and documentation.

Though I admit my capabilities may simply be lacking, I have tried to review the code of this Android App, and I cannot find the correct configuration for sending data to the actual server.

Currently build.gradle points to things like localhost, but I do not see the required configuration for actuall pointing to the real backend.

I hope this request makes sense, if there is additional information required to build and use the app please add this as well.

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by hvisser** [comment]
The environments are set in the build file using flavours. I suggest we merge this with #14 and close this issue if you are OK with that?

**Comment by hvisser** [comment]
Please see the updated steps in #14  for further discussion.
