### ISSUE TITLE
[VWS/Covid19NotificationApp] No clear message to update Google play services

### ISSUE THREAD

**Issue by jorants** [minvws/nl-covid19-notification-app-android#25]
### Describe the bug, issue or concern

When open the app for the first time it does not detect that Play Services needs updating and lets me continue through the beginning explanations until I hit the screen to activate. Here the button does nothing.
The phone does show a notification in the notification drawer, but this is easily missed, even more so due to all the information being shown in the app.

### Expected behavior
Do not continue as long as Play Services is not updated.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S5
 - OS: Android 6.0.1
 - Browser: Chrome
 - Version: Current play store version

### Additional context
-

### Governance
- [X] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [X] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [X] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by hvisser** [comment]
We do have a check for Play Services version that is too low, so that's odd, especially if you see the notification from Play Services too. Do you know what version you were on? The "button does nothing" issue sounds like #22.

Unfortunately it's not just Play Services that needs to be up to date, additional components are also installed in the background after updating. It appears that the error resulting in that case is not reported back to the app.

**Comment by hvisser** [comment]
Could you also let us know if the app is working for you now or if you are still running in to this issue? After some time the components should have been updated on the device which should resolve the issue.

**Comment by hvisser** [comment]
For the Play Services check I've updated the required version in https://github.com/minvws/nl-covid19-notification-app-android/commit/01fbcb1473b9a8dcd574957241394890e3014ea8 which should make sure the update screen will be shown when Play Services is out of date.

**Comment by jorants** [comment]
> Could you also let us know if the app is working for you now or if you are still running in to this issue? After some time the components should have been updated on the device which should resolve the issue.

There was no issue getting things to work, I just had to update play services, but less experienced users might have been confused.

**Comment by hvisser** [comment]
OK, in that case the fix that was added should fix this for new users. Going to close this then, thanks for raising the issue!
