### ISSUE TITLE
2020-08-28 [want-to-have]: guidance and documentation about how different phones notify the user about the usage of the corona phone service by the app.

### ISSUE THREAD

**Issue by ardje** [minvws/nl-covid19-notification-app-android#26]
### Describe the bug, issue or concern

No clear notifications and no notification log.

### To Reproduce
That's the issue :-(

My wife is running around with the application installed and enabled on the phone. We are not part of the test region.
Yet, she got notifications about dates she would have been in close contact with someone diagnosed with corona, on dates she was nowhere near anyone from the testing region.
She is not tech savvy, so the notifications are lost, and I can not see what exactly the notification said.

### Expected behavior
Any notification should be logged and retrievable again, with debugging data if possible. There are 2 scenes for that:
- The not tech savvy person that needs someone that understands it a bit to explain what the phone is saying.
- The tech savvy person that needs to report bugs of possible false positives or anything else with logs and all.
Also I would love to have a time with possible contact too.

### Screenshots
- Insert empty android screen

**Smartphone (please complete the following information):**
Galaxy S8+ (up to date, carrier free). Application is not in the battery saver list.

To be clear: Samsung phones have a very large active bluetooth range. You can easily walk outside with a bluetooth headset playing music and walk to the other side of the street before realizing you forgot your phone.

**Comment by ardje** [comment]
* to be clear: she assumed that was the notification. It might have been another notification.
Is there a logfile I can get from her phone to see what it said?

**Comment by hvisser** [comment]
Most likely this was the "weekly summary" notification generated by the OS. For other notifications generated from CoronaMelder, the status screen will update. In case of an exposure, the screen will show a red icon an tell you the date (not time). 

Other than that the CoronaMelder app wil only notify you for cases where the app isn't working correctly. That will take you too the app too and show you what you can do next. There's no log of notifications, the main screen in the app will show you the current status (any errors or exposure notifications).

**Comment by ardje** [comment]
@hvisser : Ok, I got it. You are right in that it's the OS. I got some screenshots from it. It's a summary that some kind of app has requested to use corona services of the OS, and the times it requested that.
It's a *red* icon :-(.
It shows only corona melder as the app. When I select that app, it notifies it couldn't "phone home" for the last 24 hours.
On my note 9, I don't get any notification at all. I will install it on more android devices.
So Coronamelder itself has indeed never ever notified.
The "last 24 hours" is a bit concerning though, but since coronamelder only interfaces the phone service to our local database, I guess it's not that harmful for now.

Anyway: I will not close this "bug" yet. I think the 24 hour bug is already mentioned.
I will retitle the bug as a need for more documentation from/for the different phone vendors to stop a panic attack for the not so tech savvy. If we can somehow give instructions to phone shops and other tech savvy people about how it works and what these notifications before the app, oh wait, that was yesterday.

**Comment by hvisser** [comment]
On the weekly notifications: we have flagged this with both Apple and Google.

We're tracking battery saving and OEM issues in #23 so I'd like to close this one if we're switching to that topic.

**Comment by ardje** [comment]
Ok, I am with you if you want to close it.
But press like this
https://www.rtlnieuws.nl/nieuws/nederland/artikel/5179852/corona-app-coronamelder-spookmeldingen-notificatie-loos-alarm
will make that the app doesn't get adopted.
And if you read more than just the headline it clarifies a bit.
*BUT* I've never seen any screenshots of what the OS says, nor any screenshot of what the Coronamelder app says. The governmental instructions should be a lot more in depth about the application, so people know what to expect.

With that, I close this ticket, thanks for making this!
