### ISSUE TITLE
No weekly notification received on my iphone

### ISSUE THREAD

**Issue by richard-1968** [minvws/nl-covid19-notification-app-android#29]
I do not get the weekly update notification from the corona melder app. On a similar iphone weekly messages are received (stating there was no contact with infected persons). Similar version of the app 1.0.5 and settings (notifications on)
My iphone is a company managed iphone (mobile iron installed)

### Expected behavior
I would expect to receive the weekly messages that there was no contact with infected persons. 

**Smartphone (please complete the following information):**
 - Device: iphone 7
 - OS: [iOS 13.6.1
 
### Governance
- [ ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by hvisser** [comment]
Thanks for the report, however this repository covers the Android code. Would you mind resubmitting here: https://github.com/minvws/nl-covid19-notification-app-ios/issues

Thanks!
