### ISSUE TITLE
EncryptedSharedPreferences might throw exception on startup under heavy load

### ISSUE THREAD

**Issue by arianvp** [minvws/nl-covid19-notification-app-android#32]
### Describe the bug, issue or concern

Both our British and German colleagues ran into serious issues with files not decrypting on the app due to `EncryptedSharedPreferences` throwing an exception when the phone is under heavy load or is just booting up (e.g. after an android update). This led to database corruption bugs in the German app. And causes the app to fail to start on both.

https://github.com/nhsx/covid-19-app-android-ag-public/issues/22

https://github.com/corona-warn-app/cwa-app-android/issues/642#issuecomment-702303270

E.g. 

### To Reproduce
Very hard to reproduce. (I haven't been able to reproduce it on this specific app yet but I did reproduce on the German counterpart) . But under high load the creation function on EncryptedSharedPreferences will throw a General security exception

### Expected behavior
we should keep retrying with exponential backoff. 
E.g. like https://github.com/corona-warn-app/cwa-app-android/blob/7ff340f673103b92ce1e37fe383fec14a6afa4e1/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/security/EncryptedPreferencesFactory.kt#L31

I only had a very superficial look at the code. So it might be that this error is already dealt with in the code without me realising.

### Screenshots

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by hvisser** [comment]
Thanks for reporting, we are aware of this issue, but since it's very hard to reproduce it's tricky to fix. Without looking at the code you referenced, a retry mechanism has the risk of hanging the entire app if not implemented correctly and it's not clear how many retries etc would be needed.

[This issue](https://issuetracker.google.com/issues/158234058) has the full discussion, and was promising a fix in the Tink library, but that seems to be delayed too :(

**Comment by hvisser** [comment]
Added a similar workaround for creating the preferences now + some work to make sure the app won't hang due this, but show a loading spinner.

**Comment by oswaldo89** [comment]
how was the problem finally solved? I've already visited all the threads where this is discussed and I can't find anything yet.

**Comment by lpappalettera** [comment]
@oswaldo89 we've implemented a retry mechanism and waiting for an update of `androidx.security:security-crypto` with a fix proper fix for it.
