### ISSUE TITLE
QR scanner

### ISSUE THREAD

**Issue by patryk1502** [minvws/nl-covid19-notification-app-android#33]
### Describe the bug, issue or concern

Beste Rijksoverheid, Kunnen jullie in de app een functie toevoegen waarmee je bij horeca zaken bijvoorbeeld een QR code scant in plaats van al je gegevens te moeten achterlaten? Zo weet de app dat je op die locatie bent geweest en kan de app je contacten ipv de horeca. Mensen zullen dan meer gemotiveerd zijn de app te gebruiken en de horeca heeft hierdoor weer meer tijd voor hun corebusiness. Daarnaast hoeven mensen zo hun persoonlijke gegevens niet bij horeca gelegenheid achter te laten. Mensen die de app niet hebben kunnen zichzelf altijd alsnog inschrijven

Dear National Government, Can you add a function to the app that allows you to scan a QR code for catering establishments, for example, instead of having to leave all your details?  This way the app knows that you have been at that location and the app can contact you instead of the catering industry.  People will then be more motivated to use the app and the hospitality industry will have more time for their core business.  In addition, people do not have to leave their personal details at a catering establishment.  People who do not have the app can always register themselves

**Comment by Kuneated** [comment]
The [CrowdNotifier](https://github.com/CrowdNotifier/documents) proposal looks quite relevant to this suggestion.

**Comment by hvisser** [comment]
Thanks for suggesting this feature!

**Comment by ChrisvanChip** [comment]
Sounds interesting, this would save time from everyone involved in a check.

Looking forward to the progress of this enchantment!

**Comment by reinier** [comment]
The current policy is to do as little as possible with private information in CoronaMelder. So even if this information will not leave the app, we don't want to introduce confusion about the purpose and privacy of the app. If the policy changes, we can take a fresh look into this.
