### ISSUE TITLE
[2020-10-22] [VWS/Covid19NotificationApp] User can mark on map that user was possible at risc

### ISSUE THREAD

**Issue by gerbenshub** [minvws/nl-covid19-notification-app-android#35]
**Information**
There may be circumstances where a user is or was at a location and would like to indicate on a map with a marker that user could maybe have been at risc (for example: supermarket too crowded).

With these markers people could be tentatively warned that they may have been at risc at xx date at xx time.

Collecting these markers can predict a possible risc spread.

This collecting or warning can be done in the background and when a certain level of user markers is reached, the notification of the app will run.

**Comment by hvisser** [comment]
Thanks for your suggestion! We'll consider it for future developments. Keep in mind that the app is never allowed to collect any location information, but if I understand you correctly you are suggesting that a user will indicate this manually, which could be an option.

**Comment by reinier** [comment]
The current policy is to do as little as possible with private information in CoronaMelder. So even if this information will not leave the app, we don't want to introduce confusion about the purpose and privacy of the app. If the policy changes, we can take a fresh look into this.
