### ISSUE TITLE
Section 'What does a notification say?' does not actually explain what a notification says

### ISSUE THREAD

**Issue by yreuvekamp** [minvws/nl-covid19-notification-app-android#36]
### Describe the bug, issue or concern

The app has a section supposedly explaining what a notification says, but it only describes what a notification will look like. It might be good to actually explain what information you will get in a notification.

### To Reproduce
1. Open app
2. Go to "What does a notification say?"

### Expected behavior
I expect a description of what a notification says, since that's the item I clicked on.

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by reinier** [comment]
Thanks, we will take the time to evaluate this in relation to the other things we want to improve in the app.

**Comment by lpappalettera** [comment]
The section label has been changed to "How do i recognize a notification?" so it suites better the purpose and content of the FAQ item.
