### ISSUE TITLE
App closes directly after open

### ISSUE THREAD

**Issue by Sauwerd** [minvws/nl-covid19-notification-app-android#39]
### Describe the bug, issue or concern

Android app closes instantly after open, displaying very shortly 'Coronamelder stopt steeds'. (nov. 3)

### Screenshots

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by hvisser** [comment]
Can you please add more details? What phone, version of Android and if you are using a custom rom?

**Comment by Sauwerd** [comment]
Galaxy J3 Pro model: SM-J330G/DS Android vs 9 
Not aware of custom version

**Comment by hvisser** [comment]
Can you try "force stopping" the app and then open it again? And as a last resort try uninstall and install the app again? This sounds like a known issue that should be fixed in the next version.

**Comment by Sauwerd** [comment]
Uninstall and then reinstall did do the trick. Issue closed.
