### ISSUE TITLE
Risk notification seems to say always test

### ISSUE THREAD

**Issue by steltenpower** [minvws/nl-covid19-notification-app-android#40]
### Describe the bug, issue or concern

In "Risk of Infection" view "What to do now?" is hidden by "Request Coronavirus test" and nothing strongly suggest there's content to scroll to.

**Smartphone (please complete the following information):**
 - Device: Moto G6plus
 - OS: Android 9

### Governance
- [X ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [X ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ X] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contr

**Comment by hvisser** [comment]
Can you elaborate on what you expect here? How do you discover that a screen in scrollable in other apps or other screens within CoronaMelder?

**Comment by steltenpower** [comment]
Ways in general that tell me there's more to scroll to: 
- seeing only the top half of characters
- whitespace at the bottom smaller than a line distance
- a sentence that is not ended yet
- a part of an image that suggests it's not the whole image. For example only the top half of a face.
- a scrollbar
- a floating arrow

The button to me just seems to be positioned perfectly in relation to the bottom of the screen, which made me think it's on purpose (and there's nothing to scroll to then), but it's a coincidence.

**Comment by hvisser** [comment]
OK, this obviously depends on the device screen size / aspect ratio, but I'll relay that feedback to our designers.

**Comment by lpappalettera** [comment]
As mentioned before, this is screen size / aspect ratio dependent. We did ask the designers of their opinion and decided to keep it as is.
