### ISSUE TITLE
App crashes when opened outside of the Netherlands.

### ISSUE THREAD

**Issue by andubadea** [minvws/nl-covid19-notification-app-android#44]
I travelled outside the Netherlands recently, and the app crashes when I tried to open it. While I realise that the app is meant to work only in the Netherlands, crashing is undesirable.

### To Reproduce
1. Travel o a location outside of the Netherlands
2. Open the app
### Device Information
 - Device: Samsunt Galaxy A8 2018
 - OS: Android 9
 - Bluetooth, Wifi and Data enabled
### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by hvisser** [comment]
The app is not dependent on location, so it's likely another crash. It might be the same as #39 since you are using a Samsung phone. You can try to force stop the app or reinstall it. 

If you are able to create a logcat output at the time of the app crashing that would be helpful.

**Comment by andubadea** [comment]
Reinstalling the app solved the issue, cannot replicate it any more. Thanks.

**Comment by hvisser** [comment]
Thanks for confirming, we should have a definitive fix for this in the next update of the app.
