### ISSUE TITLE
No introduction text when android tablet is in landscape mode

### ISSUE THREAD

**Issue by rickvanderzwet** [minvws/nl-covid19-notification-app-android#46]
![Screenshot_20201205-155510_CoronaMelder](https://user-images.githubusercontent.com/186766/101246375-3e0edd80-3713-11eb-92ca-91e144d322e1.jpg)

Version 1.1.1
Android 10
Device Samsung Galaxy Tab A

Text appears when in portrait mode. How-ever bit unintuative to see an screen without text.

**Comment by lpappalettera** [comment]
Thanks for the feedback. I will discuss this with the designers. Currently we do hide the illustration images on smaller devices, but because of the screen aspect ratio of the Samsung Galaxy Tab A it is large enough but does fill the whole screen.

**Comment by rickvanderzwet** [comment]
Hi @lpappalettera did you manage to get around discussing how you like to behave? I could try to create a patch based on the feedback.

**Comment by lpappalettera** [comment]
@rickvanderzwet yes, we're gonna hide it just like we do on small devices. The upcoming release will probably contain the fix. It's already implemented, just needs to be code review and tested. So no need for you to create a patch, thanks anyway 👍

**Comment by lpappalettera** [comment]
@rickvanderzwet FYI: issue should be fixed in version 1.2

**Comment by rickvanderzwet** [comment]
> @rickvanderzwet FYI: issue should be fixed in version 1.2

Fixed indead, Picture is not show on portait mode anymore and text is shown again.

Thanks!
