### ISSUE TITLE
No notification after exposure match

### ISSUE THREAD

**Issue by DylanSealy** [minvws/nl-covid19-notification-app-android#47]
### Describe the bug, issue or concern

I had an old notification from 16 days ago that I deleted in the app. After a few hours I heard from someone that she had received a notification, so I checked in the app, but I didn't receive one. However, on further inspection I saw in the COVID-19 Exposure Notifications settings that there was a match in one of the exposure checks.

### To Reproduce
1. Delete an old notification in the app.
2. Receive a match in an exposure check.
3. Don't receive a notification in the app.

### Expected behaviour
I expected that I would receive a notification in the app.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4
 - OS: Android 11, November security patch 
 - App version: 1.1.1 build 78961-7f22391
 - API version last check: 18204713000

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by lpappalettera** [comment]
Thanks for your report! A match in the Exposure Notification settings doesn't always result in a in app notification. It can also be a low risk exposure. Duration/distance are playing a role here. If you've been exposed to someone for a short period of time, can lead to match but won't trigger a notification. 

Not sure if that's the case here. We will have a look to see if we can reproduce it / see any issues.
