### ISSUE TITLE
Confusing message about permissions in setup wizard

### ISSUE THREAD

**Issue by matthijskooijman** [minvws/nl-covid19-notification-app-android#48]
### Describe the bug, issue or concern

During the initial setup wizard, I get the following screen:

E.g. 
![image](https://user-images.githubusercontent.com/194491/101691306-d1774400-3a6e-11eb-8ad0-1422f985adba.png)

The wording "can only warn you when ..." suggests that the bullet points specify things that are *required* for CoronaMelder to work (warn me). However, the second point says "(not necessary)", suggesting that it is optional. So which is it? If it is not necessary, then why ask? If there are other advantages to granting battery optimization permission, then which are those?

I also looked through the help/FAQ section in the app and the only question that looks related is "How much power does the app use?", but that does not mention this permission at all.

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by lpappalettera** [comment]
There were some issues with battery optimization software and background jobs. It is possible that the app works fine while the battery optimization is turned on, but because of these issues it is unreliable and it might not work correctly.

**Comment by lpappalettera** [comment]
Hopefully my last comment answered your question, otherwise feel free to reopen this issue.

**Comment by matthijskooijman** [comment]
@lpappalettera, it answers the question and I had guessed as much already, but the point of this issue was not that *I* wanted to know this per se, but that the UI is currently (at least when I report this) IMHO unclear/confusing/contradictory and would be good to improve. In that sense, I would suggest to reopen, but I'll leave that to you (I don't have permission to reopen either, it seems).

**Comment by lpappalettera** [comment]
@matthijskooijman I get it, i'll discuss this with the team and see what we can do.

**Comment by lpappalettera** [comment]
@matthijskooijman I've discussed this with the team and we've changed the text "not necessary" to "not mandatory". Hopefully this is less confusing. Suggestions are always welcome.

**Comment by matthijskooijman** [comment]
That might be slightly better, but there's still a seeming contradication between the "Can only..." and "not necessary". Looking at this again, I think the idea is to prepare people for the permissions requested, right? I could imagine changing the text above the bullet list to something like "CoronaMelder needs your permission to:" and then also change "not necessary" to "not always necessary"?

**Comment by lpappalettera** [comment]
Thanks for the suggestion, we've updated this screen in version 1.3.0 :

![device-2021-03-25-105803](https://user-images.githubusercontent.com/19887671/112455026-9e289e80-8d59-11eb-9af3-9f7e2f69e590.png)

**Comment by matthijskooijman** [comment]
Looks better to me, thanks!
