### ISSUE TITLE
Add certificate pinning to okHttpClient

### ISSUE THREAD

**Issue by TeunVR** [minvws/nl-covid19-notification-app-android#5]
To prevent mitm-attacks on the https-api.
https://square.github.io/okhttp/3.x/okhttp/okhttp3/CertificatePinner.html

**Comment by hvisser** [comment]
Thanks for raising, we're aware and tracking this internally.

**Comment by Thomvh** [comment]
Maybe stop tracking things internally. But start doing it like your German colleagues and track everything on Github. So people can join in on the development. For example: https://github.com/corona-warn-app/cwa-app-android/issues/7

**Comment by hvisser** [comment]
@Thomvh That's more of a process discussion. I'm sure we can do better next time. Thanks for the feedback.
