### ISSUE TITLE
The app has a folder just for 'publicsuffix'es while this seemed te should have removed

### ISSUE THREAD

**Issue by leek-dn** [minvws/nl-covid19-notification-app-android#50]
### The app contains a specific folder for publicsuffix(okhttp) without making sense

If one opens the app as a .zip file there is a okhttp3 folder. This folder contains but a file(and a notice) that contains public suffices.
These are .com/.nl/ names where one could register a domain name. This is not really something that one should expect inside a COVID19 app. It is quite suspicous to say the least. Can you remove this file, and the folder?

### Expected behavior
Not this file/folder to be found

**Smartphone (please complete the following information):**
 - Device: Any android device
 - OS: any Android
 - Browser None
 - Version 1.1.2

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by lpappalettera** [comment]
This file is used by OkHttp and comes with the library. It may be obsolete and possible to exclude from the project, but that sounds a bit risky to break OkHttp. I will have to look into that to see if excluding this file is something we want.

**Comment by leek-dn** [comment]
Ok thank you for your reaction
