### ISSUE TITLE
Exposure notification reappeared after +- 90 days

### ISSUE THREAD

**Issue by lucasfijen** [minvws/nl-covid19-notification-app-android#61]
### Describe the bug, issue or concern

Today I received a notification on the android app for an exposure that was 90 days ago, and for which I already had a notification back then.

I checked the google exposures, and today at the time of the notification there were 0 exposures on the moment of the notifications (which did come together with the moment google collected its exposures).

You might want to set some maximum interval after which someone can receive such notification, to prevent this kind of behaviour even when there is some bug on the backend?

**Smartphone (please complete the following information):**
 - Device: [Oneplus Nord]
 - OS: [Android 11]

### Governance
 * [x]  I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
 * [x]  I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
 * [x]  I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by lpappalettera** [comment]
Thanks for reporting this. We've got a ticket on our internal backlog regarding old exposures.

**Comment by lpappalettera** [comment]
Should be fixed in the 2.0.0 release
