### ISSUE TITLE
When giving GGD key to GGD, employee says system does not accept key

### ISSUE THREAD

**Issue by twildeman** [minvws/nl-covid19-notification-app-android#63]
### Describe the bug, issue or concern

The GGD key that my CoronaMelder App shows, is invalidated by the GGD system:
_the code is typed below; no misuse possibility, because it is invalidated_
753-QZ-ZU
_system responds with invalid key: Letter U is not allowed_

### Reproduction
There are no known steps to produce an invalid GGD key.

### Environment
**Smartphone (please complete the following information):**
 - Device: Google Pixel 4a
 - OS: Android 11 (stock)
 - Build Version: RQ3A.210705.001
 - All updates applied
 
 **CoronaMelder App:**
 - App installed from Google Play Store
 - Version: 2.2.0
 - Build: 104462-7f3badd

### Additional context
CoronaMelder installed from day 1 of public release.

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by lpappalettera** [comment]
Thanks for reporting, I've created a ticket on our internal backlog to investigate it.

**Comment by lpappalettera** [comment]
Hi @twildeman, regarding the issue. Where did you find the system response `Letter U is not allowed`? This doesn't look like one of our validation error messages and the letter `U` is a valid allowed character.

**Comment by twildeman** [comment]
The system response came from the GGD employee who called me on the phone. I haven't seen the actual message. So it is not the validation in the app. It is the validation in the GGD system backend.

**Comment by lpappalettera** [comment]
We've checked and couldn't find a way to reproduce this or any code that could lead to this error. We've also check, but the letter `U` has never been an unaccepted character. Maybe there was some miscommunication about any of the characters with the GGD employee. 

I will close this issue for now, please feel free to re-open if there is any additional info or a way to reproduce it.
