### ISSUE TITLE
App crashes after device transfer

### ISSUE THREAD

**Issue by jessehouwing** [minvws/nl-covid19-notification-app-android#65]
### Describe the bug, issue or concern

I received a new Android phone yesterday and used the Google Device Transfer option to move my apps and data from my previous Google Pixel 4 XL to the Google Pixel 6 Pro.

Upon completion Google proceeded restoring all apps, including Corona melder.

After completion of device setup, Corona Melder won't start and crashes instantly. Clearing Data & Cache for the app fixes the issue and allows me to reinitialize the app.

### To Reproduce
1. Have 2 google Android devices at hand
2. Install Corona Melder on device 1 and configure it.
3. Hard reset device 2
4. When prompted to transfer data from an old phone let device 2 copy the data from device 1
5. Complete the installation process on device 2.
6. Make sure all updates are installed and all apps have finished installing.
7. Launch Corona Melder on device 2.
8. crash.

Workaround:
1. Open the app details of Corona Melder on device 2
2. Clear data
3. Launch the app again
4. Reconfigure the app.

### Expected behavior
Ideally the app restores the configuration and automatically keeps working on the new device. If that's not possible, have the app detect the 'corrupt state', and pop up a notification to reinitialize.

At least don't crash on launch and let me reinitialize without having to manually clear the apps data.

**Smartphone (please complete the following information):**

 Device 1: 
 - Google Pixel 4 XL
 - OS: 12
 - Browser Chrome
 - Version Version 96.0.4664.104

 Device 2: 
 - Google Pixel 6 Pro
 - OS: 12
 - Browser Chrome
 - Version Version 96.0.4664.104

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by lpappalettera** [comment]
Thanks for the bug report, we will look into this.

**Comment by lpappalettera** [comment]
Issue should be fixed in version 2.5.4 of the app.
